name: Publish Guides


on:
  # Allow manual deployment
  workflow_dispatch:
  
  # Trigger when code is merged to `master` branch
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Guides
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
